<?php
function front_page_products_block_info() {

  // This example comes from node.module.
  $blocks['fpp_block'] = array(
    'info' => t('Esilehele välja toodud tooted'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function front_page_products_block_view($delta = '') {

  // This example is adapted from node.module.
  $block = array();
  switch ($delta) {
    case 'fpp_block':
      $block['subject'] = t('');
      $block['content'] = front_page_products_get_products();
      break;
  }
  return $block;
}

function front_page_products_get_products(){
   $query = db_select('node','n');
   $query -> condition('n.type','product','=');
   $query -> condition('n.status',1,'=');
   $query -> fields('n');
   $results = $query -> execute();
   $toode = '';
   while($product = $results -> fetchAssoc()){
      //krumo($product);
      $node = node_load($product['nid']);
      $toode.='<div class="col-sm-4">';
      $toode.='<div class="thumbnail product-front">';
      $image_url='';
      if(!empty($node->uc_product_image)){
          $image = $node -> uc_product_image['und'][0];
          $image_url = image_style_url('medium', $image['uri']);
      }
      $toode.='<div class="product-name">';
            $toode.= $node->title;
            $toode.='</div>';
            if(!empty($node->field_tags)){
          $tag = $node->field_tags['und'][0]['tid'];
          $tag = taxonomy_term_load($tag);
          $toode.='<div class="product-tag">';
          $toode .='<a href="'.url('taxonomy/term/'.$tag->tid).'">';
          $toode .= $tag->name;
          $toode .= '</a>';
          $toode.='</div>';
        }
         $toode.='<div class="product-picture">';
            if(!empty($image_url)){
             
              $toode.= '<img src="'.$image_url.'"></img>';
              $toode.='</div>';
            }
      if (!empty($node->body)) {
        $toode.='<div class="product-description">';
        $text = $node->body['und'][0]['value'];
        $text = substr($text,0,160);
        $toode.=$text;
        $toode .= '</div>';
}

      // if(!empty($image_url)){
      //   $toode.='<img src="'.$image_url.'">';
      // }
      
        $toode.='<div class="product-price">';
        $toode .= 'Toote hind: '.number_format($node->sell_price,2) . '$';
        $toode .= '</div>';
      $toode.= '<div class="read-more">';
      $toode.= '<a class="btn btn-default" href="'.url('node/'.$node->nid).'">'.'Vaata lähemalt'.'</a>';
      $toode.='</div>';
      $toode.='</div>';      
      $toode.='</div>';
      //krumo($node);
   }
   $output = '<div class="container-fluid">
          <div class="row">
            '.$toode.'
          </div>
        </div>';
        return $output;
}